var head = document.getElementById("heading");
console.log(head);
head.style.color = "red";
head.style.backgroundColor = "yellow";
head.style.fontSize = "50px";
head.style.border = "2px solid black";
head.style.padding = "10px";
head.style.margin = "10px";
head.style.textAlign = "center";
head.style.fontFamily = "sans-serif";
head.style.fontWeight = "bold";
head.style.borderRadius = "10px";
head.style.boxShadow = "0 0 10px black";
head.style.textShadow = "0 0 10px black";
head.style.width = "50%";